import { IconHome } from "./Components/Icons";

export const _nav = [
  {
    menuType: "single",
    name: "For Me",
    key: "For Me",
    link: "/",
    icons: <IconHome />,
    isSoon: true,
    info: "Baed on your activity",
  },
  {
    menuType: "single",
    name: "Other For You",
    key: "Other For You",
    link: "/",
    icons: <IconHome />,
    isSoon: true,
    info: "Not visited products",
  },
  {
    menuType: "single",
    name: "Within 5Km",
    key: "Within 5Km",
    link: "/",
    icons: <IconHome />,
    isSoon: true,
    info: "Products within 5Km",
  },
  {
    menuType: "multiple",
    name: "Categories",
    key: "Categories",
    link: "/",
    icons: <IconHome />,
    menuItems: [
      {
        menuType: "single",
        name: "Add",
        key: "Add",
        link: "/AddProducts",
        icons: <IconHome />,
      },
      {
        menuType: "single",
        name: "List",
        key: "List",
        link: "/ProductsList",
        icons: <IconHome />,
      },
    ],
  },
  {
    menuType: "single",
    name: "Pre Booking",
    key: 1,
    link: "/",
    icons: <IconHome />,
    info: "Only pre book products and stores",
  },
  {
    menuType: "single",
    name: "Online Payment",
    key: 2,
    link: "/",
    icons: <IconHome />,
    info: "Only online payment products and stores",
  },
  {
    menuType: "single",
    name: "Cash on Delivery",
    key: 3,
    link: "/",
    icons: <IconHome />,
    info: "Only cash on delivery products and stores",
  },
  {
    menuType: "single",
    name: "Open Shop",
    key: "Open Shop",
    link: "/",
    icons: <IconHome />,
    info: "Only open shop products and stores",
  },
  {
    menuType: "single",
    name: "Hospitals",
    key: "Hospitals",
    link: "/",
    icons: <IconHome />,
    info: "Only hospital products and stores",
  },
  {
    menuType: "single",
    name: "Hotels",
    key: "Hotels",
    link: "/",
    icons: <IconHome />,
    info: "Only hotel products and stores",
  },
];
